version: '3.3'
services:
  ui:
    build: ../alligoric
    image: cql/alligoric:latest
    ports:
      - "3000:3000"
    volumes:
      - ../alligoric:/usr/src/alligoric
      - /usr/src/alligoric/node_modules
  api:
    build: ../alligoric-api
    image: cql/alligoric-api:latest
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    volumes:
      - ../alligoric-api:/usr/src/alligoric-api
      - /usr/src/alligoric-api/node_modules
    depends_on:
      - alligoric-db
  alligoric-db:
    image: postgres:9.3
    ports:
      - 5435:5432
    volumes:
      - alligoric-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alligori
      POSTGRES_DB: alligoric
      PGDATA: /var/lib/posgresql/data/pgdata
  
volumes:
  alligoric-db-volume:
